name: ColorPalette

# Configs

configs:
  # Debug: debug
  Release: release
  # Internal: internal

# Options

options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: 12.0
    # iOS: 14.0
  bundleIdPrefix: com.skydevz
  
# Attributes

attributes:
  ORGANIZATIONNAME: SkyDevz

# packages:
#   MILocalStore:
#     path: ../../Frameworks/MILocalStore
#   Mixpanel:
#     url: https://github.com/mixpanel/mixpanel-swift
#     from: 3.1.13
#   Purchases:
#     url: https://github.com/RevenueCat/purchases-ios
#     from: 3.14.0
#   SwiftUI-Shimmer:
#     url: https://github.com/markiv/SwiftUI-Shimmer
#     from: 1.0.1
# Targets

targets:
  Color Palette:
    type: application
    platform: macOS
    sources: 
      # - path: Main/Shared
      # - path: Main/Resources
      - path: Main/macOS
    configFiles:
      # Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
      # Internal: Configs/Internal.xcconfig
    # scheme:
    #   testTargets:
    #   - UnitTests
    # postCompileScripts:
    #   - name: SwiftLint
    #     script: ./lint.sh
    # dependencies:
    #   - package: MILocalStore
    #   - package: Mixpanel
    #   - package: Purchases
    #   - package: SwiftUI-Shimmer
    #     product: Shimmer
      
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)-$(SCHEME_NAME)
    configs:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)-$(SCHEME_NAME)
        PRODUCT_NAME: $(APP_NAME)
        # DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: Main/macOS/Info.plist
      # Debug:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Development"
      # Internal:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Distribution"
      # Release:
      #   CODE_SIGN_STYLE: Automatic
      #   CODE_SIGN_IDENTITY: "Apple Distribution"
      
  # UnitTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources:
  #     - path: Main/Tests
